# Generated by Django 4.1.5 on 2023-05-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(default='name', max_length=30, unique=True)),
                ('field', models.CharField(max_length=30)),
                ('image', models.ImageField(height_field=250, upload_to='', width_field=250)),
                ('arabic', models.BooleanField(default=False)),
                ('myteam', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Frequentlyquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('ask', models.CharField(max_length=100)),
                ('arabic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Graphicdesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('mockup', models.ImageField(upload_to='')),
                ('url', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('social media', 'social media'), ('Branding', 'Branding')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mobileapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('mockup', models.ImageField(upload_to='')),
                ('url', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('allowance_of', models.IntegerField()),
                ('points', models.TextField()),
                ('arabic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('mockup', models.ImageField(upload_to='')),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('mockup', models.ImageField(upload_to='')),
                ('url', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('behance', 'behance')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
