# Generated by Django 4.1.5 on 2023-05-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conanapp', '0002_alter_allteam_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='allowance_of',
        ),
        migrations.AddField(
            model_name='services',
            name='type',
            field=models.CharField(choices=[('website', 'website'), ('ux ui', 'ux ui'), ('Motion graphic', 'Motion graphic')], default='ux ui', max_length=20),
        ),
    ]
