# Generated by Django 4.1.5 on 2023-05-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conanapp', '0003_remove_package_allowance_of_services_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
